name: cs224w
channels:
  - snap-stanford
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_1
  - pip=19.2.3=py37_0
  - pyparsing=2.4.2=py_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.2.0=py37_0
  - six=1.12.0=py37_0
  - snap-stanford=5.0.0=py37_1
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - chardet==3.0.4
    - decorator==4.4.0
    - googledrivedownloader==0.4
    - h5py==2.10.0
    - idna==2.8
    - isodate==0.6.0
    - joblib==0.14.0
    - networkx==2.4
    - pandas==0.25.2
    - plyfile==0.7.1
    - pyqt5==5.13.1
    - pyqt5-sip==4.19.19
    - rdflib==4.2.2
    - requests==2.22.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - torch==1.3.0
    - torch-cluster==1.4.5
    - torch-geometric==1.3.2
    - torch-scatter==1.3.2
    - torch-sparse==0.4.3
    - urllib3==1.25.6

